## Importing numpy

In [1]:
import numpy as np

Whenever we use any library we have refer its namespace. Here `np` is an alias of `numpy`

## NumPy Arrays

### Creating NumPy array from list

#### 1-D list

In [2]:
list_1 = [2, 3, 4, 9, 10.5]

In [3]:
print(list_1)

[2, 3, 4, 9, 10.5]


We shall use `np.array` to convert lists to numpy array

In [4]:
x = np.array(list_1)

In [9]:
print(x)

[ 2.   3.   4.   9.  10.5]


In [5]:
type(x)

numpy.ndarray

#### From 2-D list

In [6]:
list_2 = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
x2 = np.array(list_2)

In [8]:
print(x2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### From 3-D list

We shall get an n-d array where n > 2 [tensor]

In [10]:
list_3 = [[[1,2,3],[3,4,5],[5,6,7]],[[-1,-2,-4],[4,9,5],[7, 7, 8]]]

In [11]:
print(list_3)

[[[1, 2, 3], [3, 4, 5], [5, 6, 7]], [[-1, -2, -4], [4, 9, 5], [7, 7, 8]]]


In [12]:
x3 = np.array(list_3)

In [13]:
print(x3)

[[[ 1  2  3]
  [ 3  4  5]
  [ 5  6  7]]

 [[-1 -2 -4]
  [ 4  9  5]
  [ 7  7  8]]]


### Data Type

- The fundamental data structure in NumPy is `numpy.ndarray`
- Difference between numpy.ndarray and python list
  1. In numpy.ndarray the data must be homogenous (all the data should have same data type)
  2. These data types must be one of the data types (dtypes) provided by NumPy

In [14]:
homogenous_list = [1, 2, 3.5, 4, 5]

In [15]:
np.array(homogenous_list)

array([1. , 2. , 3.5, 4. , 5. ])

In [16]:
heterogenous_list = [True, 'c', 32.5]

In [17]:
np.array(heterogenous_list)

array(['True', 'c', '32.5'], dtype='<U32')

In [18]:
z = np.array([1, 2, 3])

In [19]:
type(z)

numpy.ndarray

In [20]:
type(z[0])

numpy.int32

In [21]:
z = np.array([1, 2, 3], dtype = 'float')

In [22]:
type(z)

numpy.ndarray

In [23]:
type(z[0])

numpy.float64

In [24]:
z = np.array([1, 2, 3], dtype = np.int8)

In [25]:
type(z[0])

numpy.int8

- float64: 64 bit floating point number
- int64: 64 bit integer
- int32: 32 bit integer
- int8: 8 bit integer
- bool: 8 bit True or False

### Creating NumPy from linearly spaced data using numpy.linspace

In [30]:
np.linspace(start=0, stop=20, num=11)    # d = (stop - start)/(num - 1)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [28]:
np.linspace(start=100, stop=0, num=21)

array([100.,  95.,  90.,  85.,  80.,  75.,  70.,  65.,  60.,  55.,  50.,
        45.,  40.,  35.,  30.,  25.,  20.,  15.,  10.,   5.,   0.])

In [29]:
0 - 100 / 20

-5.0

### Boolean Array

In [34]:
b = np.array([0, 1, 1, 0, 1], dtype = bool)

In [35]:
type(b[0])

numpy.bool_

In [36]:
b

array([False,  True,  True, False,  True])

### numpy.asarray and its difference with numpy.array

In [37]:
x = [1, 3 ,5, 7]

In [38]:
arr1 = np.array(x)

In [45]:
arr2 = np.asarray(x)

In [41]:
arr1

array([1, 3, 5, 7])

In [48]:
arr2

array([1, 3, 5, 7])

In [47]:
arr1 is x

False

In [46]:
arr2 is x

False

np.asarry and np.array can be used alternatively

### Creating arrays with all zero

```python

np.zeros(shape=(a,b,...))
```

In [53]:
np.zeros(shape=(5,4), dtype=np.int8)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

### Empty (uninitialized) array

In [56]:
np.empty(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### zeros_like and empty_like

In [57]:
A = np.array([[1,2],[3,4],[5,6]])

In [58]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

Create an array which is of exact shape (exact numer of rows / columns) as array A.
But all elements are initialized to zero (0)

In [59]:
np.zeros_like(A)

array([[0, 0],
       [0, 0],
       [0, 0]])

Create an uninitialized array of exact shape as array A.

In [61]:
np.empty_like(A)

array([[-1015484656,         395],
       [          0,           0],
       [          1,       32767]])

In [62]:
k = np.empty_like(A)

In [63]:
k

array([[       1095,   538970724],
       [-1012669840,         395],
       [         37,   538976288]])

In [64]:
k[0] = 34

In [65]:
k

array([[         34,          34],
       [-1012669840,         395],
       [         37,   538976288]])

### Creating arrays with all ones

In [66]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
np.ones_like(A)

array([[1, 1],
       [1, 1],
       [1, 1]])

### Identity matrix

In [68]:
np.eye(5)  ### eye name is actually borrowed from MATLAB

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

### np.arange

start is included but stop is excluded

In [71]:
np.arange(4, 25, 2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [72]:
np.arange(start=100,stop=0,step=-20)

array([100,  80,  60,  40,  20])

In [73]:
for x in range(1,10,1):
    print(x)

1
2
3
4
5
6
7
8
9


## Shape and Axes

In [83]:
x2d = np.array([[2,3,4],[9,8,7]])

In [84]:
x2d

array([[2, 3, 4],
       [9, 8, 7]])

In [85]:
x2d.shape

(2, 3)

In [86]:
x1d = np.array([1,2,3,6])

In [87]:
x1d.shape

(4,)

In [88]:
x3d = np.array([[[1,4],[2,5],[3,6]],[[7,10],[8,11],[9,12]]])

In [89]:
x3d.shape

(2, 3, 2)

### Reshaping an array

In [90]:
x2d

array([[2, 3, 4],
       [9, 8, 7]])

In [91]:
x2d.shape

(2, 3)

In [93]:
y = x2d.reshape(3, 2)

In [94]:
y.shape

(3, 2)

In [95]:
y

array([[2, 3],
       [4, 9],
       [8, 7]])

In [96]:
z = np.linspace(0,28,15)

In [97]:
z

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28.])

In [98]:
z.shape

(15,)

In [99]:
z1 = z.reshape((3,5))

In [100]:
z2 = z.reshape((5,3))

In [101]:
z1

array([[ 0.,  2.,  4.,  6.,  8.],
       [10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.]])

In [102]:
z2

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.],
       [24., 26., 28.]])

### Swaping axes

In [103]:
x = np.linspace(0, 132, 45)

In [104]:
x

array([  0.,   3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.,
        33.,  36.,  39.,  42.,  45.,  48.,  51.,  54.,  57.,  60.,  63.,
        66.,  69.,  72.,  75.,  78.,  81.,  84.,  87.,  90.,  93.,  96.,
        99., 102., 105., 108., 111., 114., 117., 120., 123., 126., 129.,
       132.])

In [105]:
x.shape

(45,)

In [106]:
x3d = x.reshape(5,3,3)

In [107]:
x3d.shape

(5, 3, 3)

In [108]:
x3d

array([[[  0.,   3.,   6.],
        [  9.,  12.,  15.],
        [ 18.,  21.,  24.]],

       [[ 27.,  30.,  33.],
        [ 36.,  39.,  42.],
        [ 45.,  48.,  51.]],

       [[ 54.,  57.,  60.],
        [ 63.,  66.,  69.],
        [ 72.,  75.,  78.]],

       [[ 81.,  84.,  87.],
        [ 90.,  93.,  96.],
        [ 99., 102., 105.]],

       [[108., 111., 114.],
        [117., 120., 123.],
        [126., 129., 132.]]])

In [110]:
x3d__ = x3d.swapaxes(0, 2)

In [111]:
x3d__.shape

(3, 3, 5)

In [112]:
x3d__

array([[[  0.,  27.,  54.,  81., 108.],
        [  9.,  36.,  63.,  90., 117.],
        [ 18.,  45.,  72.,  99., 126.]],

       [[  3.,  30.,  57.,  84., 111.],
        [ 12.,  39.,  66.,  93., 120.],
        [ 21.,  48.,  75., 102., 129.]],

       [[  6.,  33.,  60.,  87., 114.],
        [ 15.,  42.,  69.,  96., 123.],
        [ 24.,  51.,  78., 105., 132.]]])

In [113]:
y = np.linspace(0,59,60)

In [114]:
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59.])

In [115]:
y3d = y.reshape(5,3,4)

In [116]:
y3d

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]],

       [[24., 25., 26., 27.],
        [28., 29., 30., 31.],
        [32., 33., 34., 35.]],

       [[36., 37., 38., 39.],
        [40., 41., 42., 43.],
        [44., 45., 46., 47.]],

       [[48., 49., 50., 51.],
        [52., 53., 54., 55.],
        [56., 57., 58., 59.]]])

In [117]:
y3d1 = y3d.swapaxes(0,2)

In [118]:
y3d1

array([[[ 0., 12., 24., 36., 48.],
        [ 4., 16., 28., 40., 52.],
        [ 8., 20., 32., 44., 56.]],

       [[ 1., 13., 25., 37., 49.],
        [ 5., 17., 29., 41., 53.],
        [ 9., 21., 33., 45., 57.]],

       [[ 2., 14., 26., 38., 50.],
        [ 6., 18., 30., 42., 54.],
        [10., 22., 34., 46., 58.]],

       [[ 3., 15., 27., 39., 51.],
        [ 7., 19., 31., 43., 55.],
        [11., 23., 35., 47., 59.]]])

In [119]:
y3d1.shape

(4, 3, 5)

In [120]:
y3d2 = y3d.swapaxes(1,2)

In [121]:
y3d2

array([[[ 0.,  4.,  8.],
        [ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.]],

       [[12., 16., 20.],
        [13., 17., 21.],
        [14., 18., 22.],
        [15., 19., 23.]],

       [[24., 28., 32.],
        [25., 29., 33.],
        [26., 30., 34.],
        [27., 31., 35.]],

       [[36., 40., 44.],
        [37., 41., 45.],
        [38., 42., 46.],
        [39., 43., 47.]],

       [[48., 52., 56.],
        [49., 53., 57.],
        [50., 54., 58.],
        [51., 55., 59.]]])

### flatten

flatten will convert any dimensional array to 1-D array

In [124]:
y3d

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]],

       [[24., 25., 26., 27.],
        [28., 29., 30., 31.],
        [32., 33., 34., 35.]],

       [[36., 37., 38., 39.],
        [40., 41., 42., 43.],
        [44., 45., 46., 47.]],

       [[48., 49., 50., 51.],
        [52., 53., 54., 55.],
        [56., 57., 58., 59.]]])

In [125]:
y3d.shape

(5, 3, 4)

In [126]:
y_flatten = y3d.flatten()

In [127]:
y_flatten

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59.])

In [129]:
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59.])

In [134]:
y.reshape(-1,12)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.],
       [48., 49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59.]])

## Indexing and Slicing

In native python list

In [135]:
L = [1, 4, 5, 7, 8, 10, -3]

In [136]:
L[3]

7

In [137]:
L[:5]

[1, 4, 5, 7, 8]

In [138]:
L[4:]

[8, 10, -3]

In [139]:
L[3:7]

[7, 8, 10, -3]

In [140]:
L[-1]

-3

In [141]:
L[-4]

7

In [146]:
L[2:7:2]

[5, 8, -3]

In [147]:
L[::-1]

[-3, 10, 8, 7, 5, 4, 1]

numpy

In [142]:
x = np.array(L)

In [144]:
print(x)

[ 1  4  5  7  8 10 -3]


In [143]:
x[3]

7

In [145]:
x[2:5]

array([5, 7, 8])

In [148]:
x[4:]

array([ 8, 10, -3])

In [149]:
x[:5]

array([1, 4, 5, 7, 8])

In [150]:
x[1:6:2]

array([ 4,  7, 10])

In [151]:
x[-1]

-3

In [152]:
x[-3]

8

In [153]:
x[::-1]

array([-3, 10,  8,  7,  5,  4,  1])

In [170]:
x[:]

array([ 1,  4,  5,  7,  8, 10, -3])

list of list

In [158]:
L2 = [[1,3,5],[6,8,9,7],[10,12]]

In [159]:
L2

[[1, 3, 5], [6, 8, 9, 7], [10, 12]]

In [160]:
L2[1][1]

8

numpy

In [162]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [163]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [164]:
y.shape

(4, 3)

In [167]:
y[2,1]

8

In [169]:
y[2][1]

8

In [172]:
y[:,2] # -> y[0,2], y[1,2], y[2,2], y[3,2]

array([ 3,  6,  9, 12])

In [173]:
y[0,:]

array([1, 2, 3])

In [174]:
y[-1,-1]

12

In [175]:
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [176]:
y[1:3,2]

array([6, 9])

In [178]:
y[:3,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Boolean indexing

In [181]:
X = np.arange(1,11,1)

In [182]:
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [183]:
index = np.array([1, 0, 1, 1, 0, 0, 1, 1, 1, 0], dtype=bool)

In [184]:
index

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [185]:
X.shape == index.shape

True

In [186]:
X[index]

array([1, 3, 4, 7, 8, 9])

In [188]:
X[X < 5]

array([1, 2, 3, 4])

In [191]:
Z = np.array([2, 1, -3, 6, 9, 10, 23, 24, 11, -12, 3.5, 7.8, 29.33, -45.3])

In [192]:
Z[Z > 10]

array([23.  , 24.  , 11.  , 29.33])

In [194]:
Z[(Z > 5) & (Z < 15)]

array([ 6. ,  9. , 10. , 11. ,  7.8])

In [196]:
Z[(Z < 5) | (Z > 10)]

array([  2.  ,   1.  ,  -3.  ,  23.  ,  24.  ,  11.  , -12.  ,   3.5 ,
        29.33, -45.3 ])

`&` is called bitwise and operator
`|` is called bitwise or operator

In [201]:
a = np.array([False, True])
b = np.array([True, True])

In [202]:
a & b

array([False,  True])

In [203]:
a | b

array([ True,  True])